### ISSUE TITLE
Using processed datasets without a local copy of the PDB triggers download of raw data

### ISSUE THREAD

**Issue by a-r-j** [a-r-j/ProteinWorkshop#23]
Consider the following:

```bash
workshop download deep_sea_proteins
workshop train task=inverse_folding dataset=deep_sea_proteins
```

Because the `ProteinDataset` can't find all the `raw_filenames`, it triggers the download loop from the PDB.

If we however run:

```bash
workshop download pdb
workshop download deep_sea_proteins
workshop train task=inverse_folding dataset=deep_sea_proteins
```

Everything works as expected since it sees all the raw files.

### Fix

In `ProteinDataset.__init__` I suggest first looking to see if all `processed_filenames` are present and `overwrite=False` then setting `raw_filename=None` to avoid triggering the loop.

However, if we want to `overwrite=True`, then we of course need to download the raw structures.

* As part of this fix, we should consistently expose the `overwrite` arg to the user.

Thoughts @amorehead @chaitjo @Croydon-Brixton ?

**Comment by amorehead** [comment]
The fix proposed above SGTM.
