### ISSUE TITLE
Highlight local pip install option in docs

### ISSUE THREAD

**Issue by a-r-j** [a-r-j/ProteinWorkshop#29]
In the documentation we describe installation from PyPI `pip install proteinworkshop` and local installation via poetry. However, the poetry workflow can be replaced with:

```bash
git clone https://github.com/a-r-j/ProteinWorkshop/
cd ProteinWorkshop
pip install -e .
```

**Comment by amorehead** [comment]
Great find. LGTM

**Comment by amorehead** [comment]
This new [PR](https://github.com/a-r-j/ProteinWorkshop/pull/35) should address this issue.
