### ISSUE TITLE
fail to activate poetry 

### ISSUE THREAD

**Issue by pengzhangzhi** [a-r-j/ProteinWorkshop#34]
Hi, I follow the instruction and successfully install poetry but can not activate it.
```bash
prot_workshop) zpw97@daisy:~/github-projs/ProteinWorkshop$ poetry --version
Poetry (version 1.6.1)
(prot_workshop) zpw97@daisy:~/github-projs/ProteinWorkshop$ source $(poetry env info --path)/bin/activate
bash: /home/zpw97/anaconda3/envs/prot_workshop/bin/activate: No such file or directory
```

**Comment by amorehead** [comment]
Hi, @pengzhangzhi. When you run `poetry env info`, what outputs do you see?

**Comment by pengzhangzhi** [comment]
just create an env with python 3.9

**Comment by amorehead** [comment]
I see. Can you confirm that `/home/zpw97/anaconda3/envs/prot_workshop/` exists on your local device?

**Comment by pengzhangzhi** [comment]
both of them exists... I have checked them.,

**Comment by amorehead** [comment]
Out of curiosity, does the PyPI installation route work on your local machine (https://github.com/a-r-j/ProteinWorkshop#from-pypi)? If so, given the difficulties your Conda environment is causing (it may possibly be corrupted since `activate` is missing?), the PyPI route should still give you full access to the modules within `proteinworkshop`.

**Comment by pengzhangzhi** [comment]
> Hi, @pengzhangzhi. How did you set up your Conda environment `prot_workshop` out of curiosity? Also, in case it interests you, we are currently looking at replacing `poetry` with a simpler install option (per #29).

#29 actually solves the problem.

**Comment by amorehead** [comment]
Glad to hear it.

**Comment by amorehead** [comment]
FYI, for full CUDA support in PyTorch, I believe you will still need to install PyTorch CUDA yourself, before running `pip install -e .` (as mentioned here: https://github.com/a-r-j/ProteinWorkshop#from-pypi).

**Comment by pengzhangzhi** [comment]
I am not sure. I just run `pip install -e .` and have torch installed...

**Comment by amorehead** [comment]
If you run `conda list | grep torch`, do you see a CUDA version listed beside each `torch` package installed in your local environment? This should indicate whether you have the CPU or GPU-enabled version of PyTorch installed.
