### ISSUE TITLE
unable to process mmtf file to pyg

### ISSUE THREAD

**Issue by pengzhangzhi** [a-r-j/ProteinWorkshop#39]
Hi,
I try to convert a file at `'/home/zpw97/github-projs/ProteinWorkshop/proteinworkshop/data/pdb/128d.mmtf.gz'` to pyg graph.
```
graph = protein_to_pyg(
                path=path,
                chain_selection=self.chains[i]
                if self.chains is not None
                else "all",
                keep_insertions=True,
                store_het=self.store_het,
            )
```
and got the error:

```
can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.
```

**Comment by a-r-j** [comment]
Hi @pengzhangzhi thanks for raising this. Could you share the values of `self.chains[i]` for this example? I expect this is a mismatch between chians and author-assigned chains.

**Comment by pengzhangzhi** [comment]
```
self.chains[i]
'B'
```

**Comment by pengzhangzhi** [comment]
in the dataframe, I try:
```
df[df.chain_id == 'B']
```
it works.
but 
```
protein_df = filter_dataframe(
            protein_df,
            by_column="chain_id",
            list_of_values=chain_selection,
            boolean=True,
        )
```
does not work.

**Comment by a-r-j** [comment]
Ah, `128D` is a nucleic acid structure. I'd expect this fails as we can't find any protein atoms in the structure

**Comment by pengzhangzhi** [comment]
I see the problem. 128d is na, not protein. the code can not process it. that make sense!
