### ISSUE TITLE
Required batch attributes for GearNet encoder

### ISSUE THREAD

**Issue by Katja-Jagd** [a-r-j/ProteinWorkshop#73]
The required attributes when using the GearNet encoder is stated as:

        - ``x`` Positions (shape ``[num_nodes, 3]``)
        - ``edge_index`` Edge indices (shape ``[2, num_edges]``)
        - ``edge_type`` Edge types (shape ``[num_edges]``)
        - ``edge_attr`` Edge attributes (shape ``[num_edges, num_edge_features]``)
        - ``num_nodes`` Number of nodes (int)
        - ``batch`` Batch indices (shape ``[num_nodes]``)
 
In the gear_net_edge_features() method, the attribute "pos" seems to be used which is not mentioned as a required attribute. Maybe I misunderstood something but is there a chance that the required attributes list should look like this: 

        - ``pos`` Positions (shape ``[num_nodes, 3]``)
        - ``edge_index`` Edge indices (shape ``[2, num_edges]``)
        - ``edge_type`` Edge types (shape ``[num_edges]``)
        - ``edge_attr`` Edge attributes (shape ``[num_edges, num_edge_features]``)
        - ``num_nodes`` Number of nodes (int)
        - ``batch`` Batch indices (shape ``[num_nodes]``)

**Comment by a-r-j** [comment]
Thanks for spotting this @Katja-Jagd! You're absolutely correct.

**Comment by Katja-Jagd** [comment]
So just to be sure, the x is then the node features[n,d], and the pos is the node positions [n,3]? In the case of GearNet is it then correctly understood that the node features are merely  the one-hot encoding of the residue type, as described in https://arxiv.org/pdf/2203.06125.pdf (Appendix C.1)?

**Comment by a-r-j** [comment]
> So just to be sure, the x is then the node features[n,d], and the pos is the node positions [n,3]?

Yes, that is correct.

>  In the case of GearNet is it then correctly understood that the node features are merely the one-hot encoding of the residue type

This is actually configurable. GearNet is agnostic to the node features it receives; you can use any combination of the scalar features contained in the framework. You can see some documentation here: https://proteins.sh/configs/features.html
